spring:
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DATABASE}
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect