spring:
  datasource:
    url: jdbc:h2:mem:taskwill
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  main:
    banner-mode: "console"

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false


